name: Build Tauri Android App

on:
  push:
    branches:
      - master

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install project dependencies
        run: npm install

      - name: Build Android APK
        run: |
          rustup target add aarch64-linux-android
          npm run tauri android build

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-android-apk
          path: src-tauri/gen/android/app/build/outputs/apk/release/app-release.apk

