name: Build & Release Tauri Android App

on:
  push:
    branches:
      - master

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev wget unzip

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Android App
        run: |
          rustup target add aarch64-linux-android
          npm install
          npm run tauri android build

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            src-tauri/gen/android/app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
